DROP PROCEDURE GZ_CONTRACT_TRANS_ORDER
GO

CREATE PROCEDURE GZ_CONTRACT_TRANS_ORDER @CONTRACT_ID VARCHAR(32),@CODE INT output
AS

--DECLARE @UUID VARCHAR(32)
--DECLARE @CONTRACT_ID VARCHAR(32)
DECLARE @UNITID INT
DECLARE @COMMENTID INT
DECLARE @COMMENTNO VARCHAR(200)
DECLARE @ORDERINDEXID INT
--DECLARE @UUID VARCHAR(32)

BEGIN

--    SELECT @CONTRACT_ID = 'F1ACD5540AE74A5EBAA4734837E869C8'
--    SELECT @CONTRACT_ID = '74C28098E24240838EF3E571B6D8B806'
    --SELECT @UUID = REPLACE(NEWID(),'-','')
    --PRINT @UUID

    -- 第一步：ProjectUseUnit表
    INSERT INTO PROJECTUSEUNIT(USERCODE,FULLNAME,NAME,COMMENT)
    SELECT USE_UNIT_NAME,USE_UNIT_NAME,USE_UNIT_LINKMAN,PROJECT_ADDRESS  FROM GZ_PROJECT_CONTRACT WHERE CONTRACT_ID = @CONTRACT_ID
    SELECT @UNITID = @@IDENTITY
    PRINT @UNITID


    -- 第二步：ProjectCommentNo表
    SELECT @COMMENTNO = COMMON_NO  FROM GZ_PROJECT_CONTRACT WHERE CONTRACT_ID = @CONTRACT_ID
    IF (@COMMENTNO IS NULL OR LEN(RTRIM(LTRIM(@COMMENTNO)))<1) 
        BEGIN
            SELECT @COMMENTID=NULL
            PRINT 'KONG DE'
        END 
    ELSE
        BEGIN
            --PRINT @COMMENTNO
            INSERT INTO PROJECTCOMMENTNO(USERCODE,FULLNAME)
            SELECT COMMON_NO,COMMON_NO  FROM GZ_PROJECT_CONTRACT WHERE CONTRACT_ID = @CONTRACT_ID
            SELECT @COMMENTID = @@IDENTITY

            PRINT 'NIUB'
        END
    PRINT @COMMENTID

    -- 第三步：OrderIndex表
    INSERT INTO ORDERINDEX(BTYPEID,ETYPEID,BillDate,BILLCODE,Stypeid)
    SELECT DISTRIBUTOR_ID,CREATE_USER_ID,APPLY_DATE,CONTRACT_CODE,AGENCY_ID FROM GZ_PROJECT_CONTRACT WHERE CONTRACT_ID = @CONTRACT_ID
    SELECT @ORDERINDEXID = @@IDENTITY
    PRINT @ORDERINDEXID

    -- 第四步：OrderBill表
    INSERT INTO ORDERBILL(BILLNUMBERID,PTYPEID,QTY,PRICE,DISCOUNTPRICE,TAXPRICE,TOTAL,TAXTOTAL,SALETOTAL,REACHQTY,balancetypeid,PROJECTUNITID,PROJECTCOMMENTID)
    SELECT @ORDERINDEXID,PRODUCT_ID,APPLY_QUANTITY,DISTRIBUTOR_PRICE,DISTRIBUTOR_PRICE,DISTRIBUTOR_PRICE,
    APPLY_QUANTITY*DISTRIBUTOR_PRICE,APPLY_QUANTITY*DISTRIBUTOR_PRICE,APPLY_QUANTITY*DISTRIBUTOR_PRICE,0,BALANCE_TYPE,@UNITID,@COMMENTID
    FROM GZ_CONTRACT_PRODUCT WHERE CONTRACT_ID = @CONTRACT_ID

 
    SELECT @CODE = 6
    print 'Hello World!'
END
GO

