DROP VIEW GZ_SYS_USER
GO
DROP VIEW GZ_SYS_DEPT
GO
DROP VIEW GZ_PRODUCT
GO
DROP VIEW GZ_CUSTOMER
GO
DROP VIEW GZ_BRANCH
GO

CREATE VIEW GZ_BRANCH AS
SELECT TYPEID BRANCH_ID, FULLNAME BRANCH_NAME FROM STYPE
WHERE LEVEAL>0
GO
CREATE VIEW GZ_CUSTOMER AS
SELECT TYPEID CUSTOMER_ID, PARID PARENT_ID,USERCODE CUSTOMER_CODE, FULLNAME CUSTOMER_NAME,LINKMAN1 LINKMAN,LINKTEL1 LINKTEL,TELANDADDRESS ADDRESS,CreateDate CREATE_TIME FROM BTYPE
GO
CREATE VIEW GZ_PRODUCT AS
SELECT TYPEID PRODUCT_ID, PARID PARENT_ID,FULLNAME PRODUCT_NAME FROM PTYPE
GO
CREATE VIEW GZ_SYS_DEPT AS
SELECT
	D.TYPEID DEPT_ID,
	D.PARID PARENT_ID,
	'' ANCESTORS,
	D.FULLNAME DEPT_NAME,
	D.REC ORDER_NUM,
	D.LINKMAN LEADER,
	'' PHONE,
	'' EMAIL,
	'0' STATUS,
	'0' DEL_FLAG,
	NULL CREATE_BY,
	NULL CREATE_TIME,
	NULL UPDATE_BY,
	NULL UPDATE_TIME 
FROM
	DEPARTMENT D
WHERE  D.DELETED = 'false'
GO
CREATE VIEW GZ_SYS_USER AS
SELECT
	U.TYPEID USER_ID,
	ISNULL(U.DTYPEID,'00000') DEPT_ID,
	U.USERCODE LOGIN_NAME,
	U.FULLNAME USER_NAME,
	U.MAIL EMAIL,
	U.MOB PHONENUMBER,
	CASE WHEN U.SEX='false' THEN '0' ELSE '1' END SEX,
	B.AVATAR,
	B. PASSWORD,
	B.SALT,
	'0' STATUS,
	'0' DEL_FLAG ,
	B. LOGIN_IP,
	B. LOGIN_DATE,
	'' CREATE_BY,
	U.JOBTIME CREATE_TIME,
	'' UPDATE_BY,
	U.JOBTIME UPDATE_TIME,
	U.COMMENT REMARK
FROM
	EMPLOYEE U LEFT JOIN GZ_SYS_USER_EXTEND B ON U.TYPEID = B.USER_ID
WHERE  U.DELETED = 'false'
GO

